### ISSUE TITLE
etest hangs on error 400

### ISSUE THREAD

**Issue by LinoBigatti** [alunduil/etest#61]
Hello, I am trying to use etest for testing an ebuild. However, the command hangs with a 400 error message:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/lino/.local/lib/python3.8/site-packages/docker/client.py", line 170, in _raise_for_status
    response.raise_for_status()
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http+docker://localunixsocket/v1.24/containers/2a108ba7-4914-4771-9447-3adcd84c300c/start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lino/.local/lib/python3.8/site-packages/etest/__init__.py", line 61, in _
    check.run()
  File "/home/lino/.local/lib/python3.8/site-packages/etest/tests.py", line 111, in run
    is_interrupted = not docker.container.start(
  File "/home/lino/.local/lib/python3.8/site-packages/etest/docker/container.py", line 34, in start
    common.CLIENT.start(container, *args, **kwargs)
  File "/home/lino/.local/lib/python3.8/site-packages/docker/utils/decorators.py", line 21, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/home/lino/.local/lib/python3.8/site-packages/docker/api/container.py", line 383, in start
    self._raise_for_status(res)
  File "/home/lino/.local/lib/python3.8/site-packages/docker/client.py", line 174, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
docker.errors.APIError: 400 Client Error: Bad Request ("b'{"message":"starting container with non-empty request body was deprecated since API v1.22 and removed in v1.24"}'")
```

**Comment by alunduil** [comment]
Thanks for giving this a shot.  I haven't touched this project in years at this point and it's going to need quite a few updates.  I can work on updating the project structure but I'm no longer a Gentoo developer or user at this point.  Would you be interested in taking over this project if I help get it runnable again?

**Comment by LinoBigatti** [comment]
I would need to get some experience with docker first, but it sounds like a cool project! I think it could be done

**Comment by alunduil** [comment]
@LinoBigatti awesome!  I'll invite you as a collaborator to start and get this back in shape as soon as I can.  Let me know if you want anything specific to help you get up to speed on this project and its intentions.  For now, I'll consider this particular issue blocked and we can revisit this as we figure out the transition.
